server:
  port: 8002
spring:
  application:
    name: ms-qr-login
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PGC
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance: 
    hostname: localhost 